### ISSUE TITLE
Switch the current implementation to use `btree_cursors`

### ISSUE THREAD

**Issue by ripytide** [ripytide/range_bounds_map#21]
The current implementation is very much a bodge of using the `range` method largely in a unintended fashion.

Instead I propose we switch to using `btree_cursors`, which is a new API that was proposed with the express intention of improving the implementations of interval collections such as this ones this project provides.

The `btree_cursors` feature is currently a nightly unstable feature so this would more concretely lock us onto the nightly version of rust than the currently used, but more work-a-roundable features  we are using at the moment.

Overall I think this will greatly improve the simplicity of the code, and will also greatly improve the performance due to using more fit-for-purpose methods on the raw `BTreeMap`.

Related `btree_cursors` Issues and PRs
Tracking Issue: rust-lang/rust#107540
Proposal: rust-lang/libs-team#141
Implementation: rust-lang/rust#105641
Related Entry Proposal: rust-lang/libs-team#73

**Comment by ripytide** [comment]
I should probably report on my finished usage and experience after using the new feature on the tracking issue.

**Comment by ripytide** [comment]
closing in favor of #25

**Comment by workingjubilee** [comment]
> I should probably report on my finished usage and experience after using the new feature on the tracking issue, if that's the right place for feedback I'm not sure.

Probably.

**Comment by ripytide** [comment]
@workingjubilee I ended up not really using `btree_cursors` as much as I planned in favor of [ripytide/btree_monstrousity ](https://github.com/ripytide/btree_monstrousity). Hence I don't really have much feedback other than `cursors` seem useful it certain situations.
